language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: nasU8Qggy+vaE69e/MmWCwtP+gsvn13mr/J1cVfM84brWYAsvykLSvN2q+OJjmxgFZ3xW3DotscnQhcGHs1aYRG2pQLoHVMTOEX3+2HDXWEsaebNKqE7WA3wgtYPsZh5YI6qVDoK0IerSZA3lwTi69+SONRKNHznfPiMq5pi1dBUBL6QGVpYfnyhPaIybUbILHNvFGLV9CkHH5/12u8tQ2ETXYgIQ7GFKEPGJnymFusEAMaHCi6pkvpjH4ThssfQqzYMgoBbgXypK9JZUDTo6GN/m3c8MQ0tnl3quZ98kYXP16zV7m/7TiMBy9vusZXNWTZKYguBdc0k+rUdoWVtTxHWrRQ+eLiQMUk75N2npq/4PdwBQjwH+JWkiQOhdhUhYIp4wEYqbjchN4r2M9Um82SF9COijEUQVYWCG0tunJU8VxRz1AR6HoyPLAxaTewcc6E+9oOIcG8UwW2sR5Ycde8TOxCuoc3ILkiGRd+FCtIy0C3xy8S0PnzhmEzpYuMrK70WZHtnAfPm+XaCA2er3n7FA79FtNCzDmBiDHZzb/QEwcW6qeK3GEl/nJdGtbtO0ri3H7sVchlwTFSaJACuF0cytLKCj4q1mFAqputTH9ry/sRb7X5QqS4n+RDgTmoypM624sgqMFTMJd2wdOvnXanAjeoaLPsNv+FtolXj9/4=
