language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: cMggQlGidfqxMdFUXDx+onzY6zS/TCODx3jlPUtbxc7kIsZF07t5i3ig0/sMbtFFdPfa674M1CPK4IDAuxlgwAMPjV8ZYTJoduiUUabjYMIqGsOKBpaD0VPozkWlWr8c8bdtpEu/wn8jb7QFc2VO6CCsnEnOnGWCphvZG/LPMSYM94NDpATQfOaghA1OYTei6/Mzrcj8K/zTpPfaj321gWpO9NltRDvEcFno6M0nw2y0QYAx5xqTsQjrn5BDEf0rwaFPGG/QKI5qkXHNynhYfXoLdnu7MZaTnU/PjL0TrpuecFVFL9fmqq+DGnYeTIXCTN9rgsL+39sSpWsb+9kzLB8EenrWgWbF6SgEtD1ObCiaKSCOYU8+jrYjvxgY30/N9LJEdN4pp/Jivxcye6lt7/LZd4KBjlVPMejQ1/b2EDPQcLo7VXGneNREYa7vNDumhgZq6/hq4I9zPON1fyNVckoyg63lQKJLX8SmIks8TFmPUGEV+gcadXXBKG9/UuG5jya1FRKUusAWzoyvafm51F8JavDSdry7elBn4AQlLpfMzJAmrBTJXxqRtn2IhG5D0RHaw0v9IxwQ8x3+1tYoXdB+Rsj25ZrjShK1IbWt4qEzGqvKsFm20YCT8t2bywd0A5g086llsXJysc3Bd/8xoA8byRoE6G4dRXugUkA2k2A=
